### ISSUE TITLE
Add support for multitenancy wallet operations

### ISSUE THREAD

**Issue by tdiesler** [animo/agent-cli#163]
**Describe your new idea or enhancement**

Add support for the /multitenancy/wallet endpoint

**Comment by tdiesler** [comment]
I have [scripted this in bash](https://github.com/tdiesler/nessus-aries/blob/main/aries-wallet) for now

```
Usage: ./aries-wallet --[create|list|remove|switch] myname [--wallet-key mykey] [--leder-role ENDORSER]

./aries-wallet --create Faber --ledger-role ENDORSER
```

* Creates a multitenant wallet for Faber in Aca-Py
* Creates a DID for Faber
* Makes a call to the VON-Network admin page to register that DID with the ledger
* Sets the registered DID as the public DID for Faber
* Creates the Faber environment for aries-cli

**Comment by blu3beri** [comment]
Oh wow that looks awesome! It definitely sounds like something we should add.

**Comment by blu3beri** [comment]
We have added most of the multitenancy functionality in the latest 0.3.0 release.
