### ISSUE TITLE
Support out of band api in ACA-Py

### ISSUE THREAD

**Issue by TimoGlastra** [animo/agent-cli#211]
**Describe your new idea or enhancement**

I would like to use the out of band API from acapy with the agent-cli

**Comment by blu3beri** [comment]
Yeah sounds like a useful thing to support, likely some overlap with the connections API. 

I can pick this up, but I am open if someone else wants to pick this one up :).

**Comment by morrieinmaas** [comment]
i'd also be happy to pick it up
