### ISSUE TITLE
The '-i' alias for the '--connection-id' flag on the send message command not working

### ISSUE THREAD

**Issue by rapaktech** [animo/agent-cli#216]
**Describe the bug**

The '-i' alias for the '--connection-id' flag on the send message command does not work

**To Reproduce**

1. Run the 'agent-cli message -i <<ID>> -m <<message>>'

**Expected behavior**

Message should be sent

**Aries CLI version (run `aries-cli --version`)**

0.3.0

**Desktop OS**
- OS: Ubuntu
- Version: 20.04

**Verbose logs**

Run your command with the `-vvv` flag. See `aries-cli --help` for guidance.

<details>
  <summary>Logs</summary>

  ```
< error: Found argument '--i' which wasn't expected, or isn't valid in this context

	If you tried to supply `--i` as a value rather than a flag, use `-- --i`

USAGE:
    agent-cli message --connection-id <CONNECTION_ID> --message <MESSAGE>

For more information try --help
 >
  ```

</details>
<br/>

**Screenshots, screen recordings**
If applicable.

**Additional context**
I think the issue is that the alias has been changed or removed, but this has not been reflected in the docs yet.

**Comment by TimoGlastra** [comment]
Seems it is indeed not working. 

@blu3beri is the docs released from the main branch currently? Would be nice if you can update docs whenever breaking changes are made / feature are added, and that those will be released with the next version

**Comment by blu3beri** [comment]
Ah my apologies. The shorthand is `-c`. 

I will have to check how we want to deploy the docs (based on a GitHub release or on push to main).

**Comment by rapaktech** [comment]
Okay!

**Comment by rapaktech** [comment]
Should I close the issue? Or leave it for the doc fix?

**Comment by blu3beri** [comment]
> Should I close the issue? Or leave it for the doc fix?

Let's leave it for the doc fix to close it :).
